// frontend/src/components/prospects/ProspectEditModal.vue
<template>
  <Modal :isOpen="isOpen" @close="onClose" title="Edit Prospect" size="lg">
    <form @submit.prevent="handleSubmit" class="space-y-4">
      <!-- Error Message -->
      <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
        {{ error }}
      </div>

      <!-- Full Name - Read Only -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Full Name
        </label>
        <input
          type="text"
          :value="prospect?.full_name || ''"
          disabled
          class="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm bg-gray-100 text-gray-600 cursor-not-allowed"
        />
      </div>

      <!-- Connection Status -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
          Connection Status
        </label>
        <select
          class="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin"
          :value="formData.connection_status"
          @change="handleChange('connection_status', $event.target.value)"
        >
          <option
            v-for="status in Object.values(CONNECTION_STATUS)"
            :key="status"
            :value="status"
          >
            {{ CONNECTION_STATUS_LABELS[status] }}
          </option>
        </select>
      </div>

      <!-- Tags Selection -->
      <div>
        <label class="block text-sm font-medium text-gray-700 mb-2">
          Tags
        </label>
        <div class="flex flex-wrap gap-2">
          <button
            v-for="tag in availableTags"
            :key="tag.id"
            type="button"
            @click="toggleTag(tag.id)"
            :class="[
              'px-3 py-1 rounded-full text-sm font-medium transition-all',
              selectedTagIds.includes(tag.id)
                ? 'bg-linkedin text-white'
                : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
            ]"
            :style="selectedTagIds.includes(tag.id) ? {} : { borderColor: tag.color }"
          >
            {{ tag.name }}
          </button>
        </div>
        <p v-if="availableTags.length === 0" class="text-sm text-gray-500">
          No tags available. Create tags first.
        </p>
      </div>

      <!-- Action Buttons -->
      <div class="flex justify-end space-x-3 pt-4 border-t">
        <Button
          type="button"
          variant="secondary"
          @click="onClose"
        >
          Cancel
        </Button>
        <Button
          type="submit"
          variant="primary"
          :loading="updateMutation.isPending.value || attachTagsMutation.isPending.value"
        >
          Save Changes
        </Button>
      </div>
    </form>
  </Modal>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
import { useUpdateProspect, useAttachTags } from '../../composables/useProspects'
import { useTags } from '../../composables/useTags'
import { CONNECTION_STATUS, CONNECTION_STATUS_LABELS } from '../../utils/constants'
import { getErrorMessage } from '../../utils/helpers'
import Modal from '../common/Modal.vue'
import Input from '../common/Input.vue'
import Button from '../common/Button.vue'
import Tag from '../common/Tag.vue'

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true
  },
  prospect: {
    type: Object,
    default: null
  }
})

const emit = defineEmits(['close'])

const onClose = () => {
  emit('close')
}

const formData = ref({
  connection_status: CONNECTION_STATUS.NOT_CONNECTED
})
const selectedTagIds = ref([])
const error = ref('')

const updateMutation = useUpdateProspect()
const attachTagsMutation = useAttachTags()
const { data: tagsData } = useTags()
const availableTags = computed(() => Array.isArray(tagsData.value) ? tagsData.value : [])

// Initialize form data when prospect changes
watch(() => props.prospect, (newProspect) => {
  if (newProspect) {
    formData.value = {
      connection_status: newProspect.connection_status || CONNECTION_STATUS.NOT_CONNECTED
    }
    const currentTagIds = newProspect.tags?.map(t => t.id) || []
    selectedTagIds.value = currentTagIds
  }
})

const handleChange = (field, value) => {
  formData.value = { ...formData.value, [field]: value }
}

const toggleTag = (tagId) => {
  if (selectedTagIds.value.includes(tagId)) {
    selectedTagIds.value = selectedTagIds.value.filter(id => id !== tagId)
  } else {
    selectedTagIds.value = [...selectedTagIds.value, tagId]
  }
}

const handleSubmit = async () => {
  error.value = ''

  try {
    // Update prospect details
    await updateMutation.mutateAsync({
      id: props.prospect.id,
      data: formData.value
    })

    // Update tags if changed
    const currentTagIds = props.prospect.tags?.map(t => t.id) || []
    const tagsChanged = JSON.stringify([...currentTagIds].sort()) !== JSON.stringify([...selectedTagIds.value].sort())

    if (tagsChanged && selectedTagIds.value.length > 0) {
      await attachTagsMutation.mutateAsync({
        prospectId: props.prospect.id,
        tagIds: selectedTagIds.value
      })
    }

    onClose()
  } catch (err) {
    error.value = getErrorMessage(err)
  }
}
</script>

// frontend-react/src/components/prospects/ProspectEditModal.jsx
/**
 * ProspectEditModal Component
 *
 * Modal for editing prospect details and managing tags.
 */

import { useState, useEffect } from 'react';
import { useUpdateProspect, useAttachTags } from '../../hooks/useProspects';
import { useTags } from '../../hooks/useTags';
import { CONNECTION_STATUS, CONNECTION_STATUS_LABELS } from '../../utils/constants';
import { getErrorMessage } from '../../utils/helpers';
import Modal from '../common/Modal';
import Input from '../common/Input';
import Button from '../common/Button';
import Tag from '../common/Tag';

/**
 * Prospect edit modal component
 * @param {object} props - Component props
 * @param {boolean} props.isOpen - Modal open state
 * @param {function} props.onClose - Close callback
 * @param {object} props.prospect - Prospect to edit
 */
const ProspectEditModal = ({ isOpen, onClose, prospect }) => {
  const [formData, setFormData] = useState({
    connection_status: CONNECTION_STATUS.NOT_CONNECTED
  });
  const [selectedTagIds, setSelectedTagIds] = useState([]);
  const [error, setError] = useState('');

  const updateMutation = useUpdateProspect();
  const attachTagsMutation = useAttachTags();
  const { data: tagsData } = useTags();
  const availableTags = Array.isArray(tagsData) ? tagsData : [];

  // Initialize form data when prospect changes
  useEffect(() => {
    if (prospect) {
      setFormData({
        connection_status: prospect.connection_status || CONNECTION_STATUS.NOT_CONNECTED
      });

      // Set currently attached tag IDs
      const currentTagIds = prospect.tags?.map(t => t.id) || [];
      setSelectedTagIds(currentTagIds);
    }
  }, [prospect]);

  /**
   * Handle form field change
   */
  const handleChange = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  /**
   * Toggle tag selection
   */
  const toggleTag = (tagId) => {
    setSelectedTagIds(prev =>
      prev.includes(tagId)
        ? prev.filter(id => id !== tagId)
        : [...prev, tagId]
    );
  };

  /**
   * Handle form submission
   */
  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');

    try {
      // Update prospect details
      await updateMutation.mutateAsync({
        id: prospect.id,
        data: formData
      });

      // Update tags if changed
      const currentTagIds = prospect.tags?.map(t => t.id) || [];
      const tagsChanged = JSON.stringify(currentTagIds.sort()) !== JSON.stringify(selectedTagIds.sort());

      if (tagsChanged && selectedTagIds.length > 0) {
        await attachTagsMutation.mutateAsync({
          prospectId: prospect.id,
          tagIds: selectedTagIds
        });
      }

      onClose();
    } catch (err) {
      setError(getErrorMessage(err));
    }
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Edit Prospect" size="lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Error Message */}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded">
            {error}
          </div>
        )}

        {/* Full Name - Read Only */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Full Name
          </label>
          <input
            type="text"
            value={prospect?.full_name || ''}
            disabled
            className="w-full px-3 py-2 border border-gray-300 rounded-lg text-sm bg-gray-100 text-gray-600 cursor-not-allowed"
          />
        </div>

        {/* Connection Status */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">
            Connection Status
          </label>
          <select
            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin"
            value={formData.connection_status}
            onChange={(e) => handleChange('connection_status', e.target.value)}
          >
            {Object.values(CONNECTION_STATUS).map(status => (
              <option key={status} value={status}>
                {CONNECTION_STATUS_LABELS[status]}
              </option>
            ))}
          </select>
        </div>

        {/* Tags Selection */}
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-2">
            Tags
          </label>
          <div className="flex flex-wrap gap-2">
            {availableTags.map(tag => {
              const isSelected = selectedTagIds.includes(tag.id);
              return (
                <button
                  key={tag.id}
                  type="button"
                  onClick={() => toggleTag(tag.id)}
                  className={`px-3 py-1 rounded-full text-sm font-medium transition-all ${
                    isSelected
                      ? 'bg-linkedin text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                  style={isSelected ? {} : { borderColor: tag.color }}
                >
                  {tag.name}
                </button>
              );
            })}
          </div>
          {availableTags.length === 0 && (
            <p className="text-sm text-gray-500">No tags available. Create tags first.</p>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex justify-end space-x-3 pt-4 border-t">
          <Button
            type="button"
            variant="secondary"
            onClick={onClose}
          >
            Cancel
          </Button>
          <Button
            type="submit"
            variant="primary"
            loading={updateMutation.isPending || attachTagsMutation.isPending}
          >
            Save Changes
          </Button>
        </div>
      </form>
    </Modal>
  );
};

export default ProspectEditModal;
