// frontend/src/components/templates/TemplateCreateModal.jsx
/**
 * Template Create Modal
 *
 * Modal for creating new message templates (invitation, direct message, or email).
 */

import { useState, useRef } from 'react';
import Modal from '../common/Modal';
import Button from '../common/Button';
import { useCreateTemplate } from '../../hooks/useTemplates';

const TemplateCreateModal = ({ isOpen, onClose, type }) => {
  const [formData, setFormData] = useState({
    name: '',
    subject: '',
    content: '',
  });
  const [errors, setErrors] = useState({});
  const contentRef = useRef(null);
  const subjectRef = useRef(null);

  const { mutate: createTemplate, isPending } = useCreateTemplate();

  // Character limits based on type
  const getMaxLength = () => {
    if (type === 'invitation') return 300;
    if (type === 'email') return 10000;
    return 5000;
  };
  const maxLength = getMaxLength();
  const currentLength = formData.content.length;

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));

    // Clear error for this field
    if (errors[name]) {
      setErrors((prev) => ({
        ...prev,
        [name]: null,
      }));
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // Validation
    const newErrors = {};
    if (!formData.name.trim()) {
      newErrors.name = 'Template name is required';
    }
    if (type === 'email' && !formData.subject.trim()) {
      newErrors.subject = 'Email subject is required';
    }
    if (!formData.content.trim()) {
      newErrors.content = 'Message content is required';
    }
    if (formData.content.length > maxLength) {
      newErrors.content = `Message must be ${maxLength} characters or less`;
    }

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    // Build payload
    const payload = {
      name: formData.name,
      type: type,
      content: formData.content,
    };

    // Add subject for email templates
    if (type === 'email') {
      payload.subject = formData.subject;
    }

    // Create template
    createTemplate(payload, {
      onSuccess: () => {
        // Reset form and close modal
        setFormData({ name: '', subject: '', content: '' });
        setErrors({});
        onClose();
      },
      onError: (error) => {
        // Handle API errors
        if (error.response?.data?.errors) {
          setErrors(error.response.data.errors);
        }
      },
    });
  };

  const handleClose = () => {
    setFormData({ name: '', subject: '', content: '' });
    setErrors({});
    onClose();
  };

  const getTypeLabel = () => {
    if (type === 'invitation') return 'Invitation Message';
    if (type === 'email') return 'Email';
    return 'Direct Message';
  };

  const getPlaceholder = () => {
    if (type === 'invitation') {
      return "Hi {firstName}, I'd love to connect and learn more about your work...";
    }
    if (type === 'email') {
      return "Dear {firstName},\n\nI hope this email finds you well...\n\nBest regards";
    }
    return 'Write your message template here...';
  };

  const insertVariable = (variable, targetField = 'content') => {
    const ref = targetField === 'subject' ? subjectRef : contentRef;
    const input = ref.current;
    if (!input) return;

    const start = input.selectionStart;
    const end = input.selectionEnd;
    const currentValue = formData[targetField];
    const newValue = currentValue.substring(0, start) + variable + currentValue.substring(end);

    setFormData((prev) => ({
      ...prev,
      [targetField]: newValue,
    }));

    // Restore cursor position after the inserted variable
    setTimeout(() => {
      input.focus();
      input.setSelectionRange(start + variable.length, start + variable.length);
    }, 0);
  };

  const getInfoBanner = () => {
    if (type === 'invitation') {
      return (
        <div className="bg-blue-50 border-l-4 border-linkedin p-3">
          <p className="text-sm text-blue-700">
            Invitation messages are sent with connection requests and have a <strong>300 character limit</strong>.
          </p>
        </div>
      );
    }
    if (type === 'email') {
      return (
        <div className="bg-purple-50 border-l-4 border-purple-500 p-3">
          <p className="text-sm text-purple-700">
            Email templates require a <strong>subject line</strong>. Use personalization variables like{' '}
            <code className="bg-purple-100 px-1 rounded">{'{firstName}'}</code>,{' '}
            <code className="bg-purple-100 px-1 rounded">{'{fullName}'}</code>.
          </p>
        </div>
      );
    }
    return null;
  };

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title={`Create ${getTypeLabel()} Template`} size="lg">
      <form onSubmit={handleSubmit} className="space-y-4">
        {/* Template Name */}
        <div>
          <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
            Template Name <span className="text-red-500">*</span>
          </label>
          <input
            type="text"
            id="name"
            name="name"
            value={formData.name}
            onChange={handleChange}
            className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin ${
              errors.name ? 'border-red-500' : 'border-gray-300'
            }`}
            placeholder="e.g., Tech Startup Outreach"
          />
          {errors.name && <p className="text-red-500 text-sm mt-1">{errors.name}</p>}
        </div>

        {/* Email Subject (only for email type) */}
        {type === 'email' && (
          <div>
            <label htmlFor="subject" className="block text-sm font-medium text-gray-700 mb-1">
              Email Subject <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              id="subject"
              name="subject"
              ref={subjectRef}
              value={formData.subject}
              onChange={handleChange}
              className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin ${
                errors.subject ? 'border-red-500' : 'border-gray-300'
              }`}
              placeholder="e.g., Quick question about your work"
            />
            {errors.subject && <p className="text-red-500 text-sm mt-1">{errors.subject}</p>}
          </div>
        )}

        {/* Info Banner */}
        {getInfoBanner()}

        {/* Message Content */}
        <div>
          <label htmlFor="content" className="block text-sm font-medium text-gray-700 mb-1">
            {type === 'email' ? 'Email Body' : 'Message Content'} <span className="text-red-500">*</span>
          </label>
          <textarea
            id="content"
            name="content"
            ref={contentRef}
            value={formData.content}
            onChange={handleChange}
            rows={type === 'email' ? 10 : 6}
            maxLength={maxLength}
            className={`w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin resize-none ${
              errors.content ? 'border-red-500' : 'border-gray-300'
            }`}
            placeholder={getPlaceholder()}
          />
          <div className="flex justify-between items-center mt-1">
            <div>
              {errors.content && <p className="text-red-500 text-sm">{errors.content}</p>}
            </div>
            <p
              className={`text-sm ${
                currentLength > maxLength ? 'text-red-500' : 'text-gray-500'
              }`}
            >
              {currentLength} / {maxLength}
            </p>
          </div>
        </div>

        {/* Personalization Variables Help */}
        <div className="bg-gray-50 p-3 rounded-lg">
          <p className="text-xs text-gray-600 font-medium mb-2">Available Variables (click to insert):</p>
          <div className="flex flex-wrap gap-2">
            {['{firstName}', '{lastName}', '{fullName}', ...(type === 'email' ? ['{email}'] : [])].map((variable) => (
              <button
                key={variable}
                type="button"
                onClick={() => insertVariable(variable)}
                className="bg-gray-200 hover:bg-linkedin hover:text-white px-2 py-1 rounded text-xs font-mono transition-colors cursor-pointer"
              >
                {variable}
              </button>
            ))}
          </div>
        </div>

        {/* Buttons */}
        <div className="flex justify-end space-x-3 pt-4">
          <Button type="button" variant="secondary" onClick={handleClose} disabled={isPending}>
            Cancel
          </Button>
          <Button type="submit" variant="primary" disabled={isPending}>
            {isPending ? 'Creating...' : 'Create Template'}
          </Button>
        </div>
      </form>
    </Modal>
  );
};

export default TemplateCreateModal;

// frontend/src/components/templates/TemplateCreateModal.vue
<template>
  <Modal :isOpen="isOpen" :title="`Create ${typeLabel} Template`" size="lg" @close="handleClose">
    <form @submit.prevent="handleSubmit" class="space-y-4">
      <!-- Template Name -->
      <div>
        <label for="name" class="block text-sm font-medium text-gray-700 mb-1">
          Template Name <span class="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="name"
          name="name"
          :value="formData.name"
          @input="handleChange('name', $event.target.value)"
          :class="[
            'w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin',
            errors.name ? 'border-red-500' : 'border-gray-300'
          ]"
          placeholder="e.g., Tech Startup Outreach"
        />
        <p v-if="errors.name" class="text-red-500 text-sm mt-1">{{ errors.name }}</p>
      </div>

      <!-- Email Subject (only for email type) -->
      <div v-if="type === 'email'">
        <label for="subject" class="block text-sm font-medium text-gray-700 mb-1">
          Email Subject <span class="text-red-500">*</span>
        </label>
        <input
          type="text"
          id="subject"
          name="subject"
          ref="subjectRef"
          :value="formData.subject"
          @input="handleChange('subject', $event.target.value)"
          :class="[
            'w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin',
            errors.subject ? 'border-red-500' : 'border-gray-300'
          ]"
          placeholder="e.g., Quick question about your work"
        />
        <p v-if="errors.subject" class="text-red-500 text-sm mt-1">{{ errors.subject }}</p>
      </div>

      <!-- Info Banner -->
      <div v-if="type === 'invitation'" class="bg-blue-50 border-l-4 border-linkedin p-3">
        <p class="text-sm text-blue-700">
          Invitation messages are sent with connection requests and have a <strong>300 character limit</strong>.
        </p>
      </div>
      <div v-else-if="type === 'email'" class="bg-purple-50 border-l-4 border-purple-500 p-3">
        <p class="text-sm text-purple-700">
          Email templates require a <strong>subject line</strong>. Use personalization variables like
          <code class="bg-purple-100 px-1 rounded">{{ '{firstName}' }}</code>,
          <code class="bg-purple-100 px-1 rounded">{{ '{fullName}' }}</code>.
        </p>
      </div>

      <!-- Message Content -->
      <div>
        <label for="content" class="block text-sm font-medium text-gray-700 mb-1">
          {{ type === 'email' ? 'Email Body' : 'Message Content' }} <span class="text-red-500">*</span>
        </label>
        <textarea
          id="content"
          name="content"
          ref="contentRef"
          :value="formData.content"
          @input="handleChange('content', $event.target.value)"
          :rows="type === 'email' ? 10 : 6"
          :maxlength="maxLength"
          :class="[
            'w-full px-3 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-linkedin resize-none',
            errors.content ? 'border-red-500' : 'border-gray-300'
          ]"
          :placeholder="placeholder"
        />
        <div class="flex justify-between items-center mt-1">
          <div>
            <p v-if="errors.content" class="text-red-500 text-sm">{{ errors.content }}</p>
          </div>
          <p :class="['text-sm', currentLength > maxLength ? 'text-red-500' : 'text-gray-500']">
            {{ currentLength }} / {{ maxLength }}
          </p>
        </div>
      </div>

      <!-- Personalization Variables Help -->
      <div class="bg-gray-50 p-3 rounded-lg">
        <p class="text-xs text-gray-600 font-medium mb-2">Available Variables (click to insert):</p>
        <div class="flex flex-wrap gap-2">
          <button
            v-for="variable in availableVariables"
            :key="variable"
            type="button"
            @click="insertVariable(variable)"
            class="bg-gray-200 hover:bg-linkedin hover:text-white px-2 py-1 rounded text-xs font-mono transition-colors cursor-pointer"
          >
            {{ variable }}
          </button>
        </div>
      </div>

      <!-- Buttons -->
      <div class="flex justify-end space-x-3 pt-4">
        <Button type="button" variant="secondary" @click="handleClose" :disabled="isPending">
          Cancel
        </Button>
        <Button type="submit" variant="primary" :disabled="isPending">
          {{ isPending ? 'Creating...' : 'Create Template' }}
        </Button>
      </div>
    </form>
  </Modal>
</template>

<script setup>
import { ref, computed } from 'vue'
import Modal from '../common/Modal.vue'
import Button from '../common/Button.vue'
import { useCreateTemplate } from '../../composables/useTemplates'

const props = defineProps({
  isOpen: {
    type: Boolean,
    required: true
  },
  type: {
    type: String,
    required: true
  }
})

const emit = defineEmits(['close'])

const formData = ref({
  name: '',
  subject: '',
  content: '',
})
const errors = ref({})
const contentRef = ref(null)
const subjectRef = ref(null)

const { mutate: createTemplate, isPending } = useCreateTemplate()

const maxLength = computed(() => {
  if (props.type === 'invitation') return 300
  if (props.type === 'email') return 10000
  return 5000
})

const currentLength = computed(() => formData.value.content.length)

const typeLabel = computed(() => {
  if (props.type === 'invitation') return 'Invitation Message'
  if (props.type === 'email') return 'Email'
  return 'Direct Message'
})

const placeholder = computed(() => {
  if (props.type === 'invitation') {
    return "Hi {firstName}, I'd love to connect and learn more about your work..."
  }
  if (props.type === 'email') {
    return "Dear {firstName},\n\nI hope this email finds you well...\n\nBest regards"
  }
  return 'Write your message template here...'
})

const availableVariables = computed(() => {
  const vars = ['{firstName}', '{lastName}', '{fullName}']
  if (props.type === 'email') vars.push('{email}')
  return vars
})

const handleChange = (name, value) => {
  formData.value = { ...formData.value, [name]: value }

  // Clear error for this field
  if (errors.value[name]) {
    errors.value = { ...errors.value, [name]: null }
  }
}

const handleSubmit = () => {
  // Validation
  const newErrors = {}
  if (!formData.value.name.trim()) {
    newErrors.name = 'Template name is required'
  }
  if (props.type === 'email' && !formData.value.subject.trim()) {
    newErrors.subject = 'Email subject is required'
  }
  if (!formData.value.content.trim()) {
    newErrors.content = 'Message content is required'
  }
  if (formData.value.content.length > maxLength.value) {
    newErrors.content = `Message must be ${maxLength.value} characters or less`
  }

  if (Object.keys(newErrors).length > 0) {
    errors.value = newErrors
    return
  }

  // Build payload
  const payload = {
    name: formData.value.name,
    type: props.type,
    content: formData.value.content,
  }

  // Add subject for email templates
  if (props.type === 'email') {
    payload.subject = formData.value.subject
  }

  // Create template
  createTemplate(payload, {
    onSuccess: () => {
      formData.value = { name: '', subject: '', content: '' }
      errors.value = {}
      emit('close')
    },
    onError: (error) => {
      if (error.response?.data?.errors) {
        errors.value = error.response.data.errors
      }
    },
  })
}

const handleClose = () => {
  formData.value = { name: '', subject: '', content: '' }
  errors.value = {}
  emit('close')
}

const insertVariable = (variable, targetField = 'content') => {
  const input = targetField === 'subject' ? subjectRef.value : contentRef.value
  if (!input) return

  const start = input.selectionStart
  const end = input.selectionEnd
  const currentValue = formData.value[targetField]
  const newValue = currentValue.substring(0, start) + variable + currentValue.substring(end)

  formData.value = { ...formData.value, [targetField]: newValue }

  // Restore cursor position after the inserted variable
  setTimeout(() => {
    input.focus()
    input.setSelectionRange(start + variable.length, start + variable.length)
  }, 0)
}
</script>
